// Package watermark provides watermark generation for event-time processing.
//
// A watermark is a timestamp that says "no records with event time < T will arrive
// after this point." Watermarks flow through the stream as special Records
// (IsWatermark == true) and are used by the WindowOperator to decide when
// a window is complete.
//
// Watermarks are generated by the Source. The simplest strategy is to use
// the maximum timestamp seen so far minus an allowed lateness bound.
// This is the BoundedOutOfOrderness generator — the most common strategy.
package watermark

import "time"

// WatermarkGenerator creates watermark Records based on the timestamps
// of data records flowing through the stream.
//
// The Source calls OnRecord for each data record, and periodically calls
// GetWatermark to check if a new watermark should be emitted.
type WatermarkGenerator interface {
	// OnRecord updates the generator's internal state with the record's timestamp.
	OnRecord(timestamp time.Time)

	// GetWatermark returns the current watermark timestamp.
	// If no records have been seen, returns time.Time{} (zero value).
	GetWatermark() time.Time

	// CurrentWatermark returns the current watermark as a special Record
	// with IsWatermark=true. Returns the zero Record if no watermark is ready.
	CurrentWatermark() time.Time
}